name: Latest Content Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed
  workflow_dispatch:  # Allows manual trigger from GitHub Actions page

permissions:
  contents: write  # Grants permission to update the README

jobs:
  update-readme-with-content:
    name: Update README with latest blog posts and YouTube videos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Medium Posts
      - name: Fetch Medium Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@akarce"  # Your Medium RSS feed URL

      # YouTube Videos
      - name: Fetch YouTube Videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC7JlvHDfxFYKc03CwW1QjVA"  # Replace with your YouTube channel ID

      # Read existing README.md content
      - name: Read current README content
        id: readme_content
        run: |
          cat README.md > latest_content.txt

      # Update README.md with latest Medium posts and YouTube videos
      - name: Update README with latest content
        run: |
          medium_posts=$(cat medium_blog_post.txt)
          youtube_videos=$(cat youtube_video_post.txt)
          if [ -z "$medium_posts" ] && [ -z "$youtube_videos" ]; then
            echo "No new content found."
            exit 0
          fi

          existing_readme=$(cat README.md)
          # Insert both blog posts and YouTube videos into README
          updated_readme="${existing_readme//<!-- BLOG-POST-LIST:START -->/<!-- BLOG-POST-LIST:START -->\n$medium_posts}"
          updated_readme="${updated_readme//<!-- YOUTUBE-VIDEO-LIST:START -->/<!-- YOUTUBE-VIDEO-LIST:START -->\n$youtube_videos}"
          echo "$updated_readme" > README.md

      # Commit and push changes to README.md
      - name: Commit and push if updated
        run: |
          git config --local user.email "akarce@itu.edu.tr"  # Replace with your email
          git config --local user.name "Ceyhun Akar"  # Replace with your name
          git add README.md
          git commit -m "Updated README with latest blog posts and YouTube videos"
          git push
